/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as RgpdRouteImport } from './routes/rgpd'
import { Route as PresentielRouteImport } from './routes/presentiel'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as IntraRouteImport } from './routes/intra'
import { Route as InterRouteImport } from './routes/inter'
import { Route as HandicapRouteImport } from './routes/handicap'
import { Route as FoadRouteImport } from './routes/foad'
import { Route as FinancementsRouteImport } from './routes/financements'
import { Route as ElearningRouteImport } from './routes/elearning'
import { Route as DemarcheQualiteRouteImport } from './routes/demarche-qualite'
import { Route as DemarchePedagogiqueRouteImport } from './routes/demarche-pedagogique'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormationsIndexRouteImport } from './routes/formations/index'
import { Route as CertificationsRsIndexRouteImport } from './routes/certifications-rs/index'
import { Route as FormationsSc900RouteImport } from './routes/formations/sc-900'
import { Route as FormationsPythonEssentials2RouteImport } from './routes/formations/python-essentials-2'
import { Route as FormationsPythonEssentials1RouteImport } from './routes/formations/python-essentials-1'
import { Route as FormationsNetworkingEssentialsRouteImport } from './routes/formations/networking-essentials'
import { Route as FormationsMs900RouteImport } from './routes/formations/ms-900'
import { Route as FormationsLinuxEssentialsRouteImport } from './routes/formations/linux-essentials'
import { Route as FormationsIotSecurityRouteImport } from './routes/formations/iot-security'
import { Route as FormationsIotIntroductionRouteImport } from './routes/formations/iot-introduction'
import { Route as FormationsIotHackathonRouteImport } from './routes/formations/iot-hackathon'
import { Route as FormationsIotConnectingThingsRouteImport } from './routes/formations/iot-connecting-things'
import { Route as FormationsIotBigDataAnalyticsRouteImport } from './routes/formations/iot-big-data-analytics'
import { Route as FormationsEthicalHackerRouteImport } from './routes/formations/ethical-hacker'
import { Route as FormationsDevnetAssociateRouteImport } from './routes/formations/devnet-associate'
import { Route as FormationsDataAnalyticsEssentialsRouteImport } from './routes/formations/data-analytics-essentials'
import { Route as FormationsCybersecurityEssentialsRouteImport } from './routes/formations/cybersecurity-essentials'
import { Route as FormationsCyberopsRouteImport } from './routes/formations/cyberops'
import { Route as FormationsCcnaSrweRouteImport } from './routes/formations/ccna-srwe'
import { Route as FormationsCcnaItnRouteImport } from './routes/formations/ccna-itn'
import { Route as FormationsCcnaEnsaRouteImport } from './routes/formations/ccna-ensa'
import { Route as FormationsAz900RouteImport } from './routes/formations/az-900'
import { Route as FormationsAz104RouteImport } from './routes/formations/az-104'
import { Route as FormationsAi900RouteImport } from './routes/formations/ai-900'
import { Route as CertificationsRsInfrastructureReseauRouteImport } from './routes/certifications-rs/infrastructure-reseau'

const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const RgpdRoute = RgpdRouteImport.update({
  id: '/rgpd',
  path: '/rgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentielRoute = PresentielRouteImport.update({
  id: '/presentiel',
  path: '/presentiel',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const IntraRoute = IntraRouteImport.update({
  id: '/intra',
  path: '/intra',
  getParentRoute: () => rootRouteImport,
} as any)
const InterRoute = InterRouteImport.update({
  id: '/inter',
  path: '/inter',
  getParentRoute: () => rootRouteImport,
} as any)
const HandicapRoute = HandicapRouteImport.update({
  id: '/handicap',
  path: '/handicap',
  getParentRoute: () => rootRouteImport,
} as any)
const FoadRoute = FoadRouteImport.update({
  id: '/foad',
  path: '/foad',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancementsRoute = FinancementsRouteImport.update({
  id: '/financements',
  path: '/financements',
  getParentRoute: () => rootRouteImport,
} as any)
const ElearningRoute = ElearningRouteImport.update({
  id: '/elearning',
  path: '/elearning',
  getParentRoute: () => rootRouteImport,
} as any)
const DemarcheQualiteRoute = DemarcheQualiteRouteImport.update({
  id: '/demarche-qualite',
  path: '/demarche-qualite',
  getParentRoute: () => rootRouteImport,
} as any)
const DemarchePedagogiqueRoute = DemarchePedagogiqueRouteImport.update({
  id: '/demarche-pedagogique',
  path: '/demarche-pedagogique',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIndexRoute = FormationsIndexRouteImport.update({
  id: '/formations/',
  path: '/formations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRsIndexRoute = CertificationsRsIndexRouteImport.update({
  id: '/certifications-rs/',
  path: '/certifications-rs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsSc900Route = FormationsSc900RouteImport.update({
  id: '/formations/sc-900',
  path: '/formations/sc-900',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsPythonEssentials2Route =
  FormationsPythonEssentials2RouteImport.update({
    id: '/formations/python-essentials-2',
    path: '/formations/python-essentials-2',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsPythonEssentials1Route =
  FormationsPythonEssentials1RouteImport.update({
    id: '/formations/python-essentials-1',
    path: '/formations/python-essentials-1',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsNetworkingEssentialsRoute =
  FormationsNetworkingEssentialsRouteImport.update({
    id: '/formations/networking-essentials',
    path: '/formations/networking-essentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsMs900Route = FormationsMs900RouteImport.update({
  id: '/formations/ms-900',
  path: '/formations/ms-900',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsLinuxEssentialsRoute =
  FormationsLinuxEssentialsRouteImport.update({
    id: '/formations/linux-essentials',
    path: '/formations/linux-essentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsIotSecurityRoute = FormationsIotSecurityRouteImport.update({
  id: '/formations/iot-security',
  path: '/formations/iot-security',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIotIntroductionRoute =
  FormationsIotIntroductionRouteImport.update({
    id: '/formations/iot-introduction',
    path: '/formations/iot-introduction',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsIotHackathonRoute = FormationsIotHackathonRouteImport.update({
  id: '/formations/iot-hackathon',
  path: '/formations/iot-hackathon',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIotConnectingThingsRoute =
  FormationsIotConnectingThingsRouteImport.update({
    id: '/formations/iot-connecting-things',
    path: '/formations/iot-connecting-things',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsIotBigDataAnalyticsRoute =
  FormationsIotBigDataAnalyticsRouteImport.update({
    id: '/formations/iot-big-data-analytics',
    path: '/formations/iot-big-data-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsEthicalHackerRoute = FormationsEthicalHackerRouteImport.update({
  id: '/formations/ethical-hacker',
  path: '/formations/ethical-hacker',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsDevnetAssociateRoute =
  FormationsDevnetAssociateRouteImport.update({
    id: '/formations/devnet-associate',
    path: '/formations/devnet-associate',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsDataAnalyticsEssentialsRoute =
  FormationsDataAnalyticsEssentialsRouteImport.update({
    id: '/formations/data-analytics-essentials',
    path: '/formations/data-analytics-essentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsCybersecurityEssentialsRoute =
  FormationsCybersecurityEssentialsRouteImport.update({
    id: '/formations/cybersecurity-essentials',
    path: '/formations/cybersecurity-essentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormationsCyberopsRoute = FormationsCyberopsRouteImport.update({
  id: '/formations/cyberops',
  path: '/formations/cyberops',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsCcnaSrweRoute = FormationsCcnaSrweRouteImport.update({
  id: '/formations/ccna-srwe',
  path: '/formations/ccna-srwe',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsCcnaItnRoute = FormationsCcnaItnRouteImport.update({
  id: '/formations/ccna-itn',
  path: '/formations/ccna-itn',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsCcnaEnsaRoute = FormationsCcnaEnsaRouteImport.update({
  id: '/formations/ccna-ensa',
  path: '/formations/ccna-ensa',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsAz900Route = FormationsAz900RouteImport.update({
  id: '/formations/az-900',
  path: '/formations/az-900',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsAz104Route = FormationsAz104RouteImport.update({
  id: '/formations/az-104',
  path: '/formations/az-104',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsAi900Route = FormationsAi900RouteImport.update({
  id: '/formations/ai-900',
  path: '/formations/ai-900',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRsInfrastructureReseauRoute =
  CertificationsRsInfrastructureReseauRouteImport.update({
    id: '/certifications-rs/infrastructure-reseau',
    path: '/certifications-rs/infrastructure-reseau',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/certifications': typeof CertificationsRoute
  '/demarche-pedagogique': typeof DemarchePedagogiqueRoute
  '/demarche-qualite': typeof DemarcheQualiteRoute
  '/elearning': typeof ElearningRoute
  '/financements': typeof FinancementsRoute
  '/foad': typeof FoadRoute
  '/handicap': typeof HandicapRoute
  '/inter': typeof InterRoute
  '/intra': typeof IntraRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/presentiel': typeof PresentielRoute
  '/rgpd': typeof RgpdRoute
  '/temoignages': typeof TemoignagesRoute
  '/certifications-rs/infrastructure-reseau': typeof CertificationsRsInfrastructureReseauRoute
  '/formations/ai-900': typeof FormationsAi900Route
  '/formations/az-104': typeof FormationsAz104Route
  '/formations/az-900': typeof FormationsAz900Route
  '/formations/ccna-ensa': typeof FormationsCcnaEnsaRoute
  '/formations/ccna-itn': typeof FormationsCcnaItnRoute
  '/formations/ccna-srwe': typeof FormationsCcnaSrweRoute
  '/formations/cyberops': typeof FormationsCyberopsRoute
  '/formations/cybersecurity-essentials': typeof FormationsCybersecurityEssentialsRoute
  '/formations/data-analytics-essentials': typeof FormationsDataAnalyticsEssentialsRoute
  '/formations/devnet-associate': typeof FormationsDevnetAssociateRoute
  '/formations/ethical-hacker': typeof FormationsEthicalHackerRoute
  '/formations/iot-big-data-analytics': typeof FormationsIotBigDataAnalyticsRoute
  '/formations/iot-connecting-things': typeof FormationsIotConnectingThingsRoute
  '/formations/iot-hackathon': typeof FormationsIotHackathonRoute
  '/formations/iot-introduction': typeof FormationsIotIntroductionRoute
  '/formations/iot-security': typeof FormationsIotSecurityRoute
  '/formations/linux-essentials': typeof FormationsLinuxEssentialsRoute
  '/formations/ms-900': typeof FormationsMs900Route
  '/formations/networking-essentials': typeof FormationsNetworkingEssentialsRoute
  '/formations/python-essentials-1': typeof FormationsPythonEssentials1Route
  '/formations/python-essentials-2': typeof FormationsPythonEssentials2Route
  '/formations/sc-900': typeof FormationsSc900Route
  '/certifications-rs/': typeof CertificationsRsIndexRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/certifications': typeof CertificationsRoute
  '/demarche-pedagogique': typeof DemarchePedagogiqueRoute
  '/demarche-qualite': typeof DemarcheQualiteRoute
  '/elearning': typeof ElearningRoute
  '/financements': typeof FinancementsRoute
  '/foad': typeof FoadRoute
  '/handicap': typeof HandicapRoute
  '/inter': typeof InterRoute
  '/intra': typeof IntraRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/presentiel': typeof PresentielRoute
  '/rgpd': typeof RgpdRoute
  '/temoignages': typeof TemoignagesRoute
  '/certifications-rs/infrastructure-reseau': typeof CertificationsRsInfrastructureReseauRoute
  '/formations/ai-900': typeof FormationsAi900Route
  '/formations/az-104': typeof FormationsAz104Route
  '/formations/az-900': typeof FormationsAz900Route
  '/formations/ccna-ensa': typeof FormationsCcnaEnsaRoute
  '/formations/ccna-itn': typeof FormationsCcnaItnRoute
  '/formations/ccna-srwe': typeof FormationsCcnaSrweRoute
  '/formations/cyberops': typeof FormationsCyberopsRoute
  '/formations/cybersecurity-essentials': typeof FormationsCybersecurityEssentialsRoute
  '/formations/data-analytics-essentials': typeof FormationsDataAnalyticsEssentialsRoute
  '/formations/devnet-associate': typeof FormationsDevnetAssociateRoute
  '/formations/ethical-hacker': typeof FormationsEthicalHackerRoute
  '/formations/iot-big-data-analytics': typeof FormationsIotBigDataAnalyticsRoute
  '/formations/iot-connecting-things': typeof FormationsIotConnectingThingsRoute
  '/formations/iot-hackathon': typeof FormationsIotHackathonRoute
  '/formations/iot-introduction': typeof FormationsIotIntroductionRoute
  '/formations/iot-security': typeof FormationsIotSecurityRoute
  '/formations/linux-essentials': typeof FormationsLinuxEssentialsRoute
  '/formations/ms-900': typeof FormationsMs900Route
  '/formations/networking-essentials': typeof FormationsNetworkingEssentialsRoute
  '/formations/python-essentials-1': typeof FormationsPythonEssentials1Route
  '/formations/python-essentials-2': typeof FormationsPythonEssentials2Route
  '/formations/sc-900': typeof FormationsSc900Route
  '/certifications-rs': typeof CertificationsRsIndexRoute
  '/formations': typeof FormationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/certifications': typeof CertificationsRoute
  '/demarche-pedagogique': typeof DemarchePedagogiqueRoute
  '/demarche-qualite': typeof DemarcheQualiteRoute
  '/elearning': typeof ElearningRoute
  '/financements': typeof FinancementsRoute
  '/foad': typeof FoadRoute
  '/handicap': typeof HandicapRoute
  '/inter': typeof InterRoute
  '/intra': typeof IntraRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/presentiel': typeof PresentielRoute
  '/rgpd': typeof RgpdRoute
  '/temoignages': typeof TemoignagesRoute
  '/certifications-rs/infrastructure-reseau': typeof CertificationsRsInfrastructureReseauRoute
  '/formations/ai-900': typeof FormationsAi900Route
  '/formations/az-104': typeof FormationsAz104Route
  '/formations/az-900': typeof FormationsAz900Route
  '/formations/ccna-ensa': typeof FormationsCcnaEnsaRoute
  '/formations/ccna-itn': typeof FormationsCcnaItnRoute
  '/formations/ccna-srwe': typeof FormationsCcnaSrweRoute
  '/formations/cyberops': typeof FormationsCyberopsRoute
  '/formations/cybersecurity-essentials': typeof FormationsCybersecurityEssentialsRoute
  '/formations/data-analytics-essentials': typeof FormationsDataAnalyticsEssentialsRoute
  '/formations/devnet-associate': typeof FormationsDevnetAssociateRoute
  '/formations/ethical-hacker': typeof FormationsEthicalHackerRoute
  '/formations/iot-big-data-analytics': typeof FormationsIotBigDataAnalyticsRoute
  '/formations/iot-connecting-things': typeof FormationsIotConnectingThingsRoute
  '/formations/iot-hackathon': typeof FormationsIotHackathonRoute
  '/formations/iot-introduction': typeof FormationsIotIntroductionRoute
  '/formations/iot-security': typeof FormationsIotSecurityRoute
  '/formations/linux-essentials': typeof FormationsLinuxEssentialsRoute
  '/formations/ms-900': typeof FormationsMs900Route
  '/formations/networking-essentials': typeof FormationsNetworkingEssentialsRoute
  '/formations/python-essentials-1': typeof FormationsPythonEssentials1Route
  '/formations/python-essentials-2': typeof FormationsPythonEssentials2Route
  '/formations/sc-900': typeof FormationsSc900Route
  '/certifications-rs/': typeof CertificationsRsIndexRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendrier'
    | '/certifications'
    | '/demarche-pedagogique'
    | '/demarche-qualite'
    | '/elearning'
    | '/financements'
    | '/foad'
    | '/handicap'
    | '/inter'
    | '/intra'
    | '/mentions-legales'
    | '/presentiel'
    | '/rgpd'
    | '/temoignages'
    | '/certifications-rs/infrastructure-reseau'
    | '/formations/ai-900'
    | '/formations/az-104'
    | '/formations/az-900'
    | '/formations/ccna-ensa'
    | '/formations/ccna-itn'
    | '/formations/ccna-srwe'
    | '/formations/cyberops'
    | '/formations/cybersecurity-essentials'
    | '/formations/data-analytics-essentials'
    | '/formations/devnet-associate'
    | '/formations/ethical-hacker'
    | '/formations/iot-big-data-analytics'
    | '/formations/iot-connecting-things'
    | '/formations/iot-hackathon'
    | '/formations/iot-introduction'
    | '/formations/iot-security'
    | '/formations/linux-essentials'
    | '/formations/ms-900'
    | '/formations/networking-essentials'
    | '/formations/python-essentials-1'
    | '/formations/python-essentials-2'
    | '/formations/sc-900'
    | '/certifications-rs/'
    | '/formations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendrier'
    | '/certifications'
    | '/demarche-pedagogique'
    | '/demarche-qualite'
    | '/elearning'
    | '/financements'
    | '/foad'
    | '/handicap'
    | '/inter'
    | '/intra'
    | '/mentions-legales'
    | '/presentiel'
    | '/rgpd'
    | '/temoignages'
    | '/certifications-rs/infrastructure-reseau'
    | '/formations/ai-900'
    | '/formations/az-104'
    | '/formations/az-900'
    | '/formations/ccna-ensa'
    | '/formations/ccna-itn'
    | '/formations/ccna-srwe'
    | '/formations/cyberops'
    | '/formations/cybersecurity-essentials'
    | '/formations/data-analytics-essentials'
    | '/formations/devnet-associate'
    | '/formations/ethical-hacker'
    | '/formations/iot-big-data-analytics'
    | '/formations/iot-connecting-things'
    | '/formations/iot-hackathon'
    | '/formations/iot-introduction'
    | '/formations/iot-security'
    | '/formations/linux-essentials'
    | '/formations/ms-900'
    | '/formations/networking-essentials'
    | '/formations/python-essentials-1'
    | '/formations/python-essentials-2'
    | '/formations/sc-900'
    | '/certifications-rs'
    | '/formations'
  id:
    | '__root__'
    | '/'
    | '/calendrier'
    | '/certifications'
    | '/demarche-pedagogique'
    | '/demarche-qualite'
    | '/elearning'
    | '/financements'
    | '/foad'
    | '/handicap'
    | '/inter'
    | '/intra'
    | '/mentions-legales'
    | '/presentiel'
    | '/rgpd'
    | '/temoignages'
    | '/certifications-rs/infrastructure-reseau'
    | '/formations/ai-900'
    | '/formations/az-104'
    | '/formations/az-900'
    | '/formations/ccna-ensa'
    | '/formations/ccna-itn'
    | '/formations/ccna-srwe'
    | '/formations/cyberops'
    | '/formations/cybersecurity-essentials'
    | '/formations/data-analytics-essentials'
    | '/formations/devnet-associate'
    | '/formations/ethical-hacker'
    | '/formations/iot-big-data-analytics'
    | '/formations/iot-connecting-things'
    | '/formations/iot-hackathon'
    | '/formations/iot-introduction'
    | '/formations/iot-security'
    | '/formations/linux-essentials'
    | '/formations/ms-900'
    | '/formations/networking-essentials'
    | '/formations/python-essentials-1'
    | '/formations/python-essentials-2'
    | '/formations/sc-900'
    | '/certifications-rs/'
    | '/formations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendrierRoute: typeof CalendrierRoute
  CertificationsRoute: typeof CertificationsRoute
  DemarchePedagogiqueRoute: typeof DemarchePedagogiqueRoute
  DemarcheQualiteRoute: typeof DemarcheQualiteRoute
  ElearningRoute: typeof ElearningRoute
  FinancementsRoute: typeof FinancementsRoute
  FoadRoute: typeof FoadRoute
  HandicapRoute: typeof HandicapRoute
  InterRoute: typeof InterRoute
  IntraRoute: typeof IntraRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PresentielRoute: typeof PresentielRoute
  RgpdRoute: typeof RgpdRoute
  TemoignagesRoute: typeof TemoignagesRoute
  CertificationsRsInfrastructureReseauRoute: typeof CertificationsRsInfrastructureReseauRoute
  FormationsAi900Route: typeof FormationsAi900Route
  FormationsAz104Route: typeof FormationsAz104Route
  FormationsAz900Route: typeof FormationsAz900Route
  FormationsCcnaEnsaRoute: typeof FormationsCcnaEnsaRoute
  FormationsCcnaItnRoute: typeof FormationsCcnaItnRoute
  FormationsCcnaSrweRoute: typeof FormationsCcnaSrweRoute
  FormationsCyberopsRoute: typeof FormationsCyberopsRoute
  FormationsCybersecurityEssentialsRoute: typeof FormationsCybersecurityEssentialsRoute
  FormationsDataAnalyticsEssentialsRoute: typeof FormationsDataAnalyticsEssentialsRoute
  FormationsDevnetAssociateRoute: typeof FormationsDevnetAssociateRoute
  FormationsEthicalHackerRoute: typeof FormationsEthicalHackerRoute
  FormationsIotBigDataAnalyticsRoute: typeof FormationsIotBigDataAnalyticsRoute
  FormationsIotConnectingThingsRoute: typeof FormationsIotConnectingThingsRoute
  FormationsIotHackathonRoute: typeof FormationsIotHackathonRoute
  FormationsIotIntroductionRoute: typeof FormationsIotIntroductionRoute
  FormationsIotSecurityRoute: typeof FormationsIotSecurityRoute
  FormationsLinuxEssentialsRoute: typeof FormationsLinuxEssentialsRoute
  FormationsMs900Route: typeof FormationsMs900Route
  FormationsNetworkingEssentialsRoute: typeof FormationsNetworkingEssentialsRoute
  FormationsPythonEssentials1Route: typeof FormationsPythonEssentials1Route
  FormationsPythonEssentials2Route: typeof FormationsPythonEssentials2Route
  FormationsSc900Route: typeof FormationsSc900Route
  CertificationsRsIndexRoute: typeof CertificationsRsIndexRoute
  FormationsIndexRoute: typeof FormationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rgpd': {
      id: '/rgpd'
      path: '/rgpd'
      fullPath: '/rgpd'
      preLoaderRoute: typeof RgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentiel': {
      id: '/presentiel'
      path: '/presentiel'
      fullPath: '/presentiel'
      preLoaderRoute: typeof PresentielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intra': {
      id: '/intra'
      path: '/intra'
      fullPath: '/intra'
      preLoaderRoute: typeof IntraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inter': {
      id: '/inter'
      path: '/inter'
      fullPath: '/inter'
      preLoaderRoute: typeof InterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handicap': {
      id: '/handicap'
      path: '/handicap'
      fullPath: '/handicap'
      preLoaderRoute: typeof HandicapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foad': {
      id: '/foad'
      path: '/foad'
      fullPath: '/foad'
      preLoaderRoute: typeof FoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financements': {
      id: '/financements'
      path: '/financements'
      fullPath: '/financements'
      preLoaderRoute: typeof FinancementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elearning': {
      id: '/elearning'
      path: '/elearning'
      fullPath: '/elearning'
      preLoaderRoute: typeof ElearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demarche-qualite': {
      id: '/demarche-qualite'
      path: '/demarche-qualite'
      fullPath: '/demarche-qualite'
      preLoaderRoute: typeof DemarcheQualiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demarche-pedagogique': {
      id: '/demarche-pedagogique'
      path: '/demarche-pedagogique'
      fullPath: '/demarche-pedagogique'
      preLoaderRoute: typeof DemarchePedagogiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/': {
      id: '/formations/'
      path: '/formations'
      fullPath: '/formations/'
      preLoaderRoute: typeof FormationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications-rs/': {
      id: '/certifications-rs/'
      path: '/certifications-rs'
      fullPath: '/certifications-rs/'
      preLoaderRoute: typeof CertificationsRsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/sc-900': {
      id: '/formations/sc-900'
      path: '/formations/sc-900'
      fullPath: '/formations/sc-900'
      preLoaderRoute: typeof FormationsSc900RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/python-essentials-2': {
      id: '/formations/python-essentials-2'
      path: '/formations/python-essentials-2'
      fullPath: '/formations/python-essentials-2'
      preLoaderRoute: typeof FormationsPythonEssentials2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/python-essentials-1': {
      id: '/formations/python-essentials-1'
      path: '/formations/python-essentials-1'
      fullPath: '/formations/python-essentials-1'
      preLoaderRoute: typeof FormationsPythonEssentials1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/networking-essentials': {
      id: '/formations/networking-essentials'
      path: '/formations/networking-essentials'
      fullPath: '/formations/networking-essentials'
      preLoaderRoute: typeof FormationsNetworkingEssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/ms-900': {
      id: '/formations/ms-900'
      path: '/formations/ms-900'
      fullPath: '/formations/ms-900'
      preLoaderRoute: typeof FormationsMs900RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/linux-essentials': {
      id: '/formations/linux-essentials'
      path: '/formations/linux-essentials'
      fullPath: '/formations/linux-essentials'
      preLoaderRoute: typeof FormationsLinuxEssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/iot-security': {
      id: '/formations/iot-security'
      path: '/formations/iot-security'
      fullPath: '/formations/iot-security'
      preLoaderRoute: typeof FormationsIotSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/iot-introduction': {
      id: '/formations/iot-introduction'
      path: '/formations/iot-introduction'
      fullPath: '/formations/iot-introduction'
      preLoaderRoute: typeof FormationsIotIntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/iot-hackathon': {
      id: '/formations/iot-hackathon'
      path: '/formations/iot-hackathon'
      fullPath: '/formations/iot-hackathon'
      preLoaderRoute: typeof FormationsIotHackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/iot-connecting-things': {
      id: '/formations/iot-connecting-things'
      path: '/formations/iot-connecting-things'
      fullPath: '/formations/iot-connecting-things'
      preLoaderRoute: typeof FormationsIotConnectingThingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/iot-big-data-analytics': {
      id: '/formations/iot-big-data-analytics'
      path: '/formations/iot-big-data-analytics'
      fullPath: '/formations/iot-big-data-analytics'
      preLoaderRoute: typeof FormationsIotBigDataAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/ethical-hacker': {
      id: '/formations/ethical-hacker'
      path: '/formations/ethical-hacker'
      fullPath: '/formations/ethical-hacker'
      preLoaderRoute: typeof FormationsEthicalHackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/devnet-associate': {
      id: '/formations/devnet-associate'
      path: '/formations/devnet-associate'
      fullPath: '/formations/devnet-associate'
      preLoaderRoute: typeof FormationsDevnetAssociateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/data-analytics-essentials': {
      id: '/formations/data-analytics-essentials'
      path: '/formations/data-analytics-essentials'
      fullPath: '/formations/data-analytics-essentials'
      preLoaderRoute: typeof FormationsDataAnalyticsEssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/cybersecurity-essentials': {
      id: '/formations/cybersecurity-essentials'
      path: '/formations/cybersecurity-essentials'
      fullPath: '/formations/cybersecurity-essentials'
      preLoaderRoute: typeof FormationsCybersecurityEssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/cyberops': {
      id: '/formations/cyberops'
      path: '/formations/cyberops'
      fullPath: '/formations/cyberops'
      preLoaderRoute: typeof FormationsCyberopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/ccna-srwe': {
      id: '/formations/ccna-srwe'
      path: '/formations/ccna-srwe'
      fullPath: '/formations/ccna-srwe'
      preLoaderRoute: typeof FormationsCcnaSrweRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/ccna-itn': {
      id: '/formations/ccna-itn'
      path: '/formations/ccna-itn'
      fullPath: '/formations/ccna-itn'
      preLoaderRoute: typeof FormationsCcnaItnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/ccna-ensa': {
      id: '/formations/ccna-ensa'
      path: '/formations/ccna-ensa'
      fullPath: '/formations/ccna-ensa'
      preLoaderRoute: typeof FormationsCcnaEnsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/az-900': {
      id: '/formations/az-900'
      path: '/formations/az-900'
      fullPath: '/formations/az-900'
      preLoaderRoute: typeof FormationsAz900RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/az-104': {
      id: '/formations/az-104'
      path: '/formations/az-104'
      fullPath: '/formations/az-104'
      preLoaderRoute: typeof FormationsAz104RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/ai-900': {
      id: '/formations/ai-900'
      path: '/formations/ai-900'
      fullPath: '/formations/ai-900'
      preLoaderRoute: typeof FormationsAi900RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications-rs/infrastructure-reseau': {
      id: '/certifications-rs/infrastructure-reseau'
      path: '/certifications-rs/infrastructure-reseau'
      fullPath: '/certifications-rs/infrastructure-reseau'
      preLoaderRoute: typeof CertificationsRsInfrastructureReseauRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendrierRoute: CalendrierRoute,
  CertificationsRoute: CertificationsRoute,
  DemarchePedagogiqueRoute: DemarchePedagogiqueRoute,
  DemarcheQualiteRoute: DemarcheQualiteRoute,
  ElearningRoute: ElearningRoute,
  FinancementsRoute: FinancementsRoute,
  FoadRoute: FoadRoute,
  HandicapRoute: HandicapRoute,
  InterRoute: InterRoute,
  IntraRoute: IntraRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PresentielRoute: PresentielRoute,
  RgpdRoute: RgpdRoute,
  TemoignagesRoute: TemoignagesRoute,
  CertificationsRsInfrastructureReseauRoute:
    CertificationsRsInfrastructureReseauRoute,
  FormationsAi900Route: FormationsAi900Route,
  FormationsAz104Route: FormationsAz104Route,
  FormationsAz900Route: FormationsAz900Route,
  FormationsCcnaEnsaRoute: FormationsCcnaEnsaRoute,
  FormationsCcnaItnRoute: FormationsCcnaItnRoute,
  FormationsCcnaSrweRoute: FormationsCcnaSrweRoute,
  FormationsCyberopsRoute: FormationsCyberopsRoute,
  FormationsCybersecurityEssentialsRoute:
    FormationsCybersecurityEssentialsRoute,
  FormationsDataAnalyticsEssentialsRoute:
    FormationsDataAnalyticsEssentialsRoute,
  FormationsDevnetAssociateRoute: FormationsDevnetAssociateRoute,
  FormationsEthicalHackerRoute: FormationsEthicalHackerRoute,
  FormationsIotBigDataAnalyticsRoute: FormationsIotBigDataAnalyticsRoute,
  FormationsIotConnectingThingsRoute: FormationsIotConnectingThingsRoute,
  FormationsIotHackathonRoute: FormationsIotHackathonRoute,
  FormationsIotIntroductionRoute: FormationsIotIntroductionRoute,
  FormationsIotSecurityRoute: FormationsIotSecurityRoute,
  FormationsLinuxEssentialsRoute: FormationsLinuxEssentialsRoute,
  FormationsMs900Route: FormationsMs900Route,
  FormationsNetworkingEssentialsRoute: FormationsNetworkingEssentialsRoute,
  FormationsPythonEssentials1Route: FormationsPythonEssentials1Route,
  FormationsPythonEssentials2Route: FormationsPythonEssentials2Route,
  FormationsSc900Route: FormationsSc900Route,
  CertificationsRsIndexRoute: CertificationsRsIndexRoute,
  FormationsIndexRoute: FormationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
